# semeru.conf — Semeru targets pre-defined per arch
our %targets;

%targets = (%targets,
  "semeru-xa64" => {
    inherit_from => [ "linux-x86_64" ],
    shlib_variant => "-semeru",
  },
  "semeru-xr64" => {
    inherit_from => [ "linux-aarch64" ],
    shlib_variant => "-semeru",
  },
  "semeru-xl64" => {
    inherit_from => [ "linux-ppc64le" ],
    shlib_variant => "-semeru",
  },
  "semeru-xz64" => {
    inherit_from => [ "linux64-s390x" ],
    shlib_variant => "-semeru",
  },
);
